---
- name: Enabling remi repo
  shell: |
       wget https://rpms.remirepo.net/enterprise/remi-release-7.rpm
       rpm -Uvh remi-release-7.rpm
       yum --disablerepo="*" --enablerepo="remi-safe" list php[7-9][0-9].x86_64
       yum-config-manager --enable remi-php74
       rm -f remi-release-7.rpm

- name: PHP and related packages installation
  yum: 
       name: "{{ php_packages }}"
       state: present

- name: Copying modified www.conf file
  copy:
       src: www.conf.j2
       dest: /etc/php-fpm.d/www.conf
       owner: root
       group: root
       mode: 0644
  notify: services restart
